"""
Streamlit chat interface for the RAG pipeline.

Imports query/ask.py's ask() directly rather than re-implementing retrieval
or generation — this app is a thin UI layer over the same pipeline the CLI
uses. Defaults to the Hugging Face free Serverless Inference backend, since
this is the public-facing deployment and there's no billing risk on a free
HF token (no payment method on file, so the worst case is a slow or failed
response, never a surprise bill). Claude and Ollama stay available as CLI
flags for local testing/comparison (see query/ask.py) but are not exposed
here, specifically so a public visitor can never trigger a paid API call.
"""

import os
import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent / "query"))

from ask import ask  # noqa: E402

BACKEND = "huggingface"


def _resolve_hf_token() -> str | None:
    """Bridge st.secrets (deployed app) into the HF_TOKEN env var ask.py already
    reads, so ask.py itself never needs to know Streamlit exists. Falls back to
    a locally-exported env var for `streamlit run app.py` during development."""
    try:
        if "HF_TOKEN" in st.secrets:
            return st.secrets["HF_TOKEN"]
    except Exception:
        pass
    return os.environ.get("HF_TOKEN")


token = _resolve_hf_token()
if token:
    os.environ["HF_TOKEN"] = token

st.set_page_config(page_title="Ask My Archive", page_icon="📚")

st.title("📚 Ask My Archive")
st.caption(
    "Ask questions about Vanna Winland's published writing on AI and software "
    "engineering, answered from her actual essays with citations."
)

with st.form("ask_form"):
    question = st.text_input(
        "Your question",
        placeholder="e.g. What has Vanna written about AI and code review?",
        label_visibility="collapsed",
    )
    submitted = st.form_submit_button("Ask", use_container_width=True)

if submitted:
    if not question.strip():
        st.warning("Enter a question first.")
    else:
        with st.spinner("Searching the archive and drafting an answer..."):
            result = ask(question.strip(), backend=BACKEND)

        if result.error:
            st.info(f"Couldn't get an answer this time: {result.error}")
        else:
            st.markdown("### Answer")
            st.write(result.answer)

            st.markdown("### Sources")
            if result.sources:
                for s in result.sources:
                    st.markdown(f"- [{s['title']}]({s['url']})")
            else:
                st.caption("No specific essay was cited for this answer.")

st.divider()
st.caption(
    "Answers are generated by a free Hugging Face model grounded only in "
    "excerpts retrieved from the essay archive — if the archive doesn't cover "
    "a topic, the model is instructed to say so rather than guess."
)
